{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-thymeleaf",
    "version": "3.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.7"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf-spring6",
          "version": {
            "requires": "3.1.3.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.5.7.jar",
          "url": "spring-boot-starter-thymeleaf-3.5.7.jar",
          "size": 4771,
          "sha512": "d39bc61cc255abc3729709d6c900baaab81abd9386254c85fed60502fcb2f5247dbedf725c52a3a87b7e0ce9a8a5ad608c190700b909001bd57cdca47882a330",
          "sha256": "e9d09b586349408984226de0a45e1e35e8c3cdd38cb0795e60394f0250ff4e20",
          "sha1": "5981cf00d4cf2fd93b59f69e9ed24dcf8592bcad",
          "md5": "c4e002bd12994783073b208b818fb13d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.5.7"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf-spring6",
          "version": {
            "requires": "3.1.3.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.5.7.jar",
          "url": "spring-boot-starter-thymeleaf-3.5.7.jar",
          "size": 4771,
          "sha512": "d39bc61cc255abc3729709d6c900baaab81abd9386254c85fed60502fcb2f5247dbedf725c52a3a87b7e0ce9a8a5ad608c190700b909001bd57cdca47882a330",
          "sha256": "e9d09b586349408984226de0a45e1e35e8c3cdd38cb0795e60394f0250ff4e20",
          "sha1": "5981cf00d4cf2fd93b59f69e9ed24dcf8592bcad",
          "md5": "c4e002bd12994783073b208b818fb13d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.5.7-javadoc.jar",
          "url": "spring-boot-starter-thymeleaf-3.5.7-javadoc.jar",
          "size": 4771,
          "sha512": "d39bc61cc255abc3729709d6c900baaab81abd9386254c85fed60502fcb2f5247dbedf725c52a3a87b7e0ce9a8a5ad608c190700b909001bd57cdca47882a330",
          "sha256": "e9d09b586349408984226de0a45e1e35e8c3cdd38cb0795e60394f0250ff4e20",
          "sha1": "5981cf00d4cf2fd93b59f69e9ed24dcf8592bcad",
          "md5": "c4e002bd12994783073b208b818fb13d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-3.5.7-sources.jar",
          "url": "spring-boot-starter-thymeleaf-3.5.7-sources.jar",
          "size": 4771,
          "sha512": "d39bc61cc255abc3729709d6c900baaab81abd9386254c85fed60502fcb2f5247dbedf725c52a3a87b7e0ce9a8a5ad608c190700b909001bd57cdca47882a330",
          "sha256": "e9d09b586349408984226de0a45e1e35e8c3cdd38cb0795e60394f0250ff4e20",
          "sha1": "5981cf00d4cf2fd93b59f69e9ed24dcf8592bcad",
          "md5": "c4e002bd12994783073b208b818fb13d"
        }
      ]
    }
  ]
}
