{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-configuration-processor",
    "version": "3.5.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.5.7.jar",
          "url": "spring-boot-configuration-processor-3.5.7.jar",
          "size": 135473,
          "sha512": "6f60ebcd9de7a77a665f545fba6d295dcf1628b17ef1332ed43c38d9294ee80d1e31d79da937a7ca719575e0f1cdff9bad1a7fb8ecf630ba213ecc31c99ccfbe",
          "sha256": "1f832e58e3ef6d9b3797840aff1c6f0d02db1703735c907ad6abbd6e0ae81135",
          "sha1": "18e7a39068a84cd401d758162a5a23a8b8b47b22",
          "md5": "1281163a407730abdac18121fac0c655"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.5.7.jar",
          "url": "spring-boot-configuration-processor-3.5.7.jar",
          "size": 135473,
          "sha512": "6f60ebcd9de7a77a665f545fba6d295dcf1628b17ef1332ed43c38d9294ee80d1e31d79da937a7ca719575e0f1cdff9bad1a7fb8ecf630ba213ecc31c99ccfbe",
          "sha256": "1f832e58e3ef6d9b3797840aff1c6f0d02db1703735c907ad6abbd6e0ae81135",
          "sha1": "18e7a39068a84cd401d758162a5a23a8b8b47b22",
          "md5": "1281163a407730abdac18121fac0c655"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.5.7-javadoc.jar",
          "url": "spring-boot-configuration-processor-3.5.7-javadoc.jar",
          "size": 194218,
          "sha512": "6876cdbc7a11b295df984b6867800ff9f0490a9495dd9ffe92683e021487f5f7b2c516964ea0256702b14f2ca44222d9247ca31c0c6bcfb6122a0829a3e027f4",
          "sha256": "610c5426d918da1d968bc483747f18e60b9f51e73865d4bd9c19e5c9ad505271",
          "sha1": "96abb33794829d600e3d16017414e1c1d733e504",
          "md5": "fbab32d98a3fe23d0c44766313cde707"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.5.7-sources.jar",
          "url": "spring-boot-configuration-processor-3.5.7-sources.jar",
          "size": 88317,
          "sha512": "a678b6dbd121d928a7e9cf26e20a710c913cf0c8ddcde1fbc5608ef5abc64e861d70490089271447180b5400a486d46579a97ae437dd00c1e3585230796c6e41",
          "sha256": "110d603ec7f8991140613706560be0f410deaadf69ed33c7327432f70e4179c6",
          "sha1": "42630a2b6f0f97bf628361afc068f40ebb98dbec",
          "md5": "372af28cccfedb541d7f147a2ab860cc"
        }
      ]
    }
  ]
}
